name    'ericsson-netbackup'
version '0.2.0'
source 'https://github.com/Ericsson/puppet-module-netbackup.git'
author 'ericsson'
license 'Apache License, Version 2.0'
summary 'Manage NetBackup'
description 'Manage NetBackup'
project_page 'https://github.com/Ericsson/puppet-module-netbackup'

dependency 'puppetlabs/stdlib',   '>= 3.2.0'
